name: "Yor Git Metadata Tagging"
description: "Composite action to tag Terraform files with Yor Git metadata and optionally commit them."

inputs:
  terraform-dir:
    description: "Relative path to the directory containing Terraform configuration files (e.g., 'tf', 'infrastructure')."
    required: false
    type: string
    default: "tf"

  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string
    default: ""

  commit-changes:
    description: "Whether to commit tagged files. Accepts 'true' or 'false'."
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Set Checkout Ref
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.set-ref.outputs.ref }}
        fetch-depth: 0

    - name: Run yor action
      uses: bridgecrewio/yor-action@main
      env:
        LOG_LEVEL: DEBUG
      with:
        version: 0.1.129
        directory: ${ inputs.terraform-dir }
        skip_directory: test
        tag: git_modifiers,git_commit,git_repository,yor_trace
        tag_groups: git,code2cloud
        # custom_tags: path/to/plugin.so
        output_format: json

    # - name: Run Yor tagging
    #   shell: bash
    #   run: |
    #     echo "Tagging Terraform files in ${{ inputs.terraform-dir }}..."
    #     yor tag -d "${{ inputs.terraform-dir }}"

    # - name: Show git diff after tagging
    #   shell: bash
    #   run: |
    #     echo "Modified files:"
    #     git --no-pager diff --name-only "${{ inputs.terraform-dir }}"
    #     echo "----"
    #     git --no-pager diff "${{ inputs.terraform-dir }}"

    # - name: Write Summary of Modified Files
    #   shell: bash
    #   run: |
    #     {
    #       echo "### ðŸ·ï¸ Yor Git Metadata Tags Summary"
    #       echo ""
    #       echo "**Modified files:**"
    #       git diff --name-only "${{ inputs.terraform-dir }}" | sed 's/^/- /'
    #     } >> $GITHUB_STEP_SUMMARY

    # - name: Commit Yor tags
    #   if: ${{ inputs.commit-changes == 'true' }}
    #   shell: bash
    #   run: |
    #     if [[ "$GITHUB_EVENT_NAME" == "pull_request" || "$GITHUB_REPOSITORY" == *"/fork" ]]; then
    #       echo "Skipping commit on pull request or fork"
    #       exit 0
    #     fi

    #     git config user.name "github-actions"
    #     git config user.email "github-actions@github.com"
    #     git add "${{ inputs.terraform-dir }}"
    #     git commit -m "chore: add Yor Git metadata tags" || echo "No changes to commit"
    #     git push
